### PR TITLE
BugFix in image_generator function in raw.py & Add comment to cine.py

### PR DESCRIPTION
**Pull request by ehki**
1. There was a BUG in image_generator function in raw.py. The bug is Fixed.
2. Add comment to the cine.py according to the following Phantom Cine File Format document:
http://phantomhighspeed-knowledge.force.com/servlet/fileField?id=0BE1N000000kD2i

### CODE REVIEW

**Comment by ehki** [comment]
Hi,
Sorry, there is a conflict. 
I think this is not so severe. Could you resolve?
I have to learn how to use Github more fluently.

**Comment by ehki** [comment]
I think I managed to solve the conflict.

**Comment by cbenhagen** [comment]
Hi,

there are way too many commits in this PR. Please squash and/or rebase. Also please open one PR per thing you want to fix or add. This makes it easier to discuss and review.

Wouldn't it be nicer if we had all those comments as docstrings instead?

**Comment by cbenhagen** [comment]
I think you just used your old branch again for this PR. I suggest you pull your master to my master and create one branch per PR from there. Let me know if you need clearer instructions for this. I am on my phone right now but can give you more details about how I work later.

**Comment by cbenhagen** [comment]
Assuming you start from fresh in a new directory (you can skip this part):
```
git clone https://github.com/ehki/pycine.git
```

Add upstream remote:
```
git remote add upstream https://github.com/OTTOMATIC-IO/pycine.git
```

No whenever you want to keep your fork up to date you can do:
```
git checkout master
git pull upstream master
git push
```

Don't do anything on this master branch. Always create branches from there:
```
git checkout -b your_fix
```

To work on another fix, go back to master and create a new branch from there:
```
git checkout master
git checkout -b new_feature
```

**Comment by ehki** [comment]
Could I withdraw this PR once?
I organize my branches and will submit one or two PR again.

**Comment by cbenhagen** [comment]
Not sure if I understand the question. You can just close it and open two new PRs.

**Comment by cbenhagen** [comment]
Oh, I just saw that you already committed stuff to the master of your fork. You might want to fix that first (but after you added the upstream remote):

```
git checkout master
git reset --hard upstream/master
git push
```

**Pull request closed without merging**
